/*
 * Void, a modification for grok.com
 * Copyright (c) 2026 Void contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export const SERIALIZE = {
    DEFAULT_DEPTH: 2,
    MAX_ARRAY: 20,
    MAX_KEYS: 15,
    MAX_STRING_LENGTH: 120,
} as const;

export const SEARCH = {
    MAX_TOTAL: 20_000,
    DEFAULT_MAX: 10,
    DEFAULT_CONTEXT: 50,
    MAX_CONTEXT: 200,
    MAX_RESULTS_CAP: 50,
    MAX_MATCH_LENGTH: 300,
} as const;

export const MODULE = {
    DEFAULT_SOURCE_LIMIT: 4000,
    MAX_SOURCE_LIMIT: 50_000,
    EXPORT_VALUE_SLICE: 30,
    EXPORT_KEYS_PREVIEW: 3,
    DEFAULT_EXPORT_KEYS: 30,
    MAX_EXPORT_KEYS: 80,
    DEFAULT_DIFF_SLICE: 3000,
    MAX_DIFF_SLICE: 10_000,
    DEFAULT_FIND_ALL: 10,
    MAX_FIND_ALL: 50,
    DEFAULT_WHERE_USED: 30,
    MAX_WHERE_USED: 200,
    SUGGEST_MIN_LEN: 6,
    DEFAULT_SUGGEST: 20,
    MAX_SUGGEST: 50,
    FUNCTION_AT_MAX: 8000,
    FUNCTION_AT_HEADER_MAX: 200,
    FUNCTION_AT_FORWARD: 500,
    FUNCTION_AT_LOOKBACK: 200,
    DIFF_CONTEXT_PAD: 40,
    DIFF_SCAN_LIMIT: 5000,
    DIFF_RESYNC_SLICE: 20,
    DIFF_UNSYNCED_CONTEXT: 150,
    EXPORT_KEYS_SLICE: 8,
    SEARCH_CONTEXT_PAD: 150,
    DEFAULT_UNLOADED_LIMIT: 15,
    MAX_UNLOADED_LIMIT: 50,
    UNLOADED_PREVIEW_LENGTH: 80,
    MAX_SHARED_WITH: 5,
    DEFAULT_NAMED_EXPORTS: 30,
    MAX_NAMED_EXPORTS: 100,
} as const;

export const PATCH = {
    FIND_SLICE: 80,
    ANALYZE_IDS_LIMIT: 10,
    NOT_UNIQUE_IDS_LIMIT: 5,
    MATCH_SLICE: 150,
    GROUP_SLICE: 60,
    DEFAULT_CONTEXT_PAD: 120,
    MAX_CONTEXT_PAD: 500,
    HINT_LITERAL_SLICE: 25,
    MAX_CAPTURE_WARN: 5,
    CONTEXT_DEFAULT_WINDOW: 1200,
    CONTEXT_MAX_WINDOW: 5000,
    CONTEXT_MIN_WINDOW: 50,
    CONTEXT_MAX_ANCHORS: 20,
    MATCH_WARN_LENGTH: 80,
    MATCH_LONG_LENGTH: 200,
    ANALYZE_DEFAULT_CONTEXT: 200,
    MIN_LITERAL_LENGTH: 3,
} as const;

export const REACT = {
    MAX_DEPTH: 30,
    DEFAULT_DEPTH: 10,
    MAX_LIMIT: 30,
    DEFAULT_LIMIT: 10,
    MAX_BREADTH: 15,
    DEFAULT_BREADTH: 5,
    MAX_TREE_DEPTH: 3,
    MAX_PROCESS: 5_000,
    MAX_NAMED: 150,
    MAX_HOOKS: 15,
    MAX_STATE_VALUES: 10,
    PROP_KEYS_PREVIEW: 5,
    FIBER_PROP_KEYS: 8,
    TEXT_SLICE: 40,
    WALK_UP_DEPTH: 5,
    MAX_CLASS_PREVIEW: 3,
    MIN_COMPONENT_NAME: 3,
} as const;

export const STORE = {
    DEFAULT_DURATION: 10_000,
    MIN_DURATION: 1000,
    MAX_DURATION: 60_000,
    DEFAULT_CAPTURES: 30,
    MAX_CAPTURES: 200,
    KEYS_PREVIEW: 8,
    SIMILAR_LIMIT: 5,
    LIST_KEYS_PREVIEW: 8,
    METHODS_PREVIEW: 8,
    MAX_DEPTH: 4,
    DEFAULT_DEPTH: 2,
    SUBSCRIBE_DEPTH: 1,
    MINIFIED_STORE_NAME: "r",
} as const;

export const INTERCEPT = {
    DEFAULT_DURATION: 30_000,
    MIN_DURATION: 5000,
    MAX_DURATION: 120_000,
    DEFAULT_CAPTURES: 30,
    MAX_CAPTURES: 200,
    GET_CAPTURES_LIMIT: 30,
    SERIALIZE_DEPTH: 2,
} as const;

export const MCP = {
    SLOW_THRESHOLD: 1000,
    MAX_RESULT_SIZE: 50_000,
    INITIAL_RECONNECT_DELAY: 3000,
    MAX_RECONNECT_DELAY: 60_000,
    TRUNCATION_THRESHOLD: 20_000,
    MIN_TRUNCATED_ITEMS: 5,
    MIN_TRUNCATED_NESTED: 3,
    REQUEST_TIMEOUT: 65_000,
    WS_OPEN: 1,
    PORT: 7890,
} as const;

export const GROK = {
    SEND_TIMEOUT: 120_000,
    MAX_RESPONSE_LENGTH: 30_000,
    MAX_THINKING_LENGTH: 10_000,
    SERIALIZE_DEPTH: 2,
} as const;

export const EVAL = {
    MAX_CODE_LENGTH: 10_000,
    SERIALIZE_DEPTH: 3,
    STACK_LINES: 3,
} as const;
